# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_id', models.CharField(default='no', max_length=20)),
                ('ISBN', models.CharField(default='no', max_length=20)),
                ('Book_name', models.CharField(default='no', max_length=20)),
                ('Price', models.CharField(default='no', max_length=20)),
                ('Author', models.CharField(default='no', max_length=20)),
            ],
        ),
    ]
